#                                             
# *Copyright 2007, 2011 CCLS Columbia University (USA), LIFO University of Orl��ans (France), BRGM (France)
# *
# *Authors: Cyril Nortet, Xiangrong Kong, Ansaf Salleb-Aouissi, Christel Vrain, Daniel Cassard
# *
# *This file is part of QuantMiner.
# *
# *QuantMiner is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
# *
# *QuantMiner is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
# *
# *You should have received a copy of the GNU General Public License along with QuantMiner.  If not, see <http://www.gnu.org/licenses/>.
# 

from src.tools import *


class DefaultPanel(DatabasePanel):

    #* Creates new form PanneauDefaut 
    def __init__(self):
        self.__jLabelFond = None

        self.__initComponents()

        self.__jLabelFond.setIcon(javax.swing.ImageIcon(ENV.REPERTOIRE_RESSOURCES + "QuantMiner.png"))

    #    * This method is called from within the constructor to
    #     * initialize the form.
    #     * WARNING: Do NOT modify this code. The content of this method is
    #     * always regenerated by the Form Editor.
    #     
    def __initComponents(self):
        self.__jLabelFond = javax.swing.JLabel()

        setLayout(java.awt.BorderLayout())

        self.__jLabelFond.setHorizontalAlignment(javax.swing.SwingConstants.CENTER)
        add(self.__jLabelFond, java.awt.BorderLayout.CENTER)
 #GEN-END:initComponents


    # Variables declaration - do not modify//GEN-BEGIN:variables
    # End of variables declaration//GEN-END:variables

