#                                             
# *Copyright 2007, 2011 CCLS Columbia University (USA), LIFO University of Orl��ans (France), BRGM (France)
# *
# *Authors: Cyril Nortet, Xiangrong Kong, Ansaf Salleb-Aouissi, Christel Vrain, Daniel Cassard
# *
# *This file is part of QuantMiner.
# *
# *QuantMiner is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
# *
# *QuantMiner is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
# *
# *You should have received a copy of the GNU General Public License along with QuantMiner.  If not, see <http://www.gnu.org/licenses/>.
# 


from src.tools import *



class DialogWindowInfoHTML(javax.swing.JDialog, HyperlinkListener):



    #* Creates new form DialogFenetreAide 
    def __init__(self, sTitre, sTexteHTMLAffiche, parent, modal):
        self.__jButtonFermer = None
        self.__jEditorPaneHTML = None
        self.__jPanelGeneral = None
        self.__jScrollPaneHTML = None

        super().__init__(parent, modal)
        self.__initComponents()

        setTitle(sTitre)
        setResizable(False)
        setLocationRelativeTo(None)

        self.__jEditorPaneHTML.setText(sTexteHTMLAffiche)
        self.__jEditorPaneHTML.setCaretPosition(0)



    #    * This method is called from within the constructor to
    #     * initialize the form.
    #     * WARNING: Do NOT modify this code. The content of this method is
    #     * always regenerated by the Form Editor.
    #     
    def __initComponents(self):
        self.__jPanelGeneral = javax.swing.JPanel()
        self.__jScrollPaneHTML = javax.swing.JScrollPane()
        self.__jEditorPaneHTML = javax.swing.JEditorPane()
        self.__jButtonFermer = javax.swing.JButton()

        setTitle("")
        addWindowListener(WindowAdapterAnonymousInnerClass(self))

        self.__jPanelGeneral.setLayout(None)

        self.__jPanelGeneral.setPreferredSize(java.awt.Dimension(700, 500))
        self.__jScrollPaneHTML.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER)
        self.__jEditorPaneHTML.setEditable(False)
        self.__jEditorPaneHTML.setContentType("text/html")
        self.__jEditorPaneHTML.setAutoscrolls(False)
        self.__jScrollPaneHTML.setViewportView(self.__jEditorPaneHTML)

        self.__jPanelGeneral.add(self.__jScrollPaneHTML)
        self.__jScrollPaneHTML.setBounds(10, 10, 680, 440)

        self.__jButtonFermer.setText("close")
        self.__jButtonFermer.addActionListener(ActionListenerAnonymousInnerClass(self))

        self.__jPanelGeneral.add(self.__jButtonFermer)
        self.__jButtonFermer.setBounds(310, 464, 75, 26)

        getContentPane().add(self.__jPanelGeneral, java.awt.BorderLayout.CENTER)

        pack() #GEN-END:initComponents

    class WindowAdapterAnonymousInnerClass(java.awt.event.WindowAdapter):

        def __init__(self, outerInstance):
            self.__outerInstance = outerInstance

        def windowClosing(self, evt):
            outerInstance.__closeDialog(evt)

    class ActionListenerAnonymousInnerClass(java.awt.event.ActionListener):

        def __init__(self, outerInstance):
            self.__outerInstance = outerInstance

        def actionPerformed(self, evt):
            outerInstance.__jButtonFermerActionPerformed(evt)



    def __jButtonFermerActionPerformed(self, evt):
        setVisible(False)
        dispose() #GEN-LAST:event_jButtonFermerActionPerformed



    #* Closes the dialog 
    def __closeDialog(self, evt):
        setVisible(False)
        dispose() #GEN-LAST:event_closeDialog

    #    *
    #     * @param args the command line arguments
    #     
    @staticmethod
    def main(args):
        (DialogWindowInfoHTML("", "", javax.swing.JFrame(), True)).show()


    def hyperlinkUpdate(self, e):
        pass



    # Variables declaration - do not modify//GEN-BEGIN:variables
    # End of variables declaration//GEN-END:variables

