#                                             
# *Copyright 2007, 2011 CCLS Columbia University (USA), LIFO University of Orl��ans (France), BRGM (France)
# *
# *Authors: Cyril Nortet, Xiangrong Kong, Ansaf Salleb-Aouissi, Christel Vrain, Daniel Cassard
# *
# *This file is part of QuantMiner.
# *
# *QuantMiner is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
# *
# *QuantMiner is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
# *
# *You should have received a copy of the GNU General Public License along with QuantMiner.  If not, see <http://www.gnu.org/licenses/>.
# 


from apriori_solver import *
from tools import *
from tools.ENV import *



class DialogParameterSetting(javax.swing.JDialog):

    __serialVersionUID = 1


    #* Creates new form DialogParametrage 
    def __init__(self, contexteResolution, parent, modal):
        self.m_iAncienLook = 0
        self.m_contexteResolution = None
        self.__buttonGroupApparence = None
        self.__jButtonAide = None
        self.__jButtonAnnuler = None
        self.__jButtonEnregistrer = None
        self.__jButtonFichierSon = None
        self.__jCheckBoxAvertir = None
        self.__jLabelApparence = None
        self.__jLabelFichierSon = None
        self.__jLabelUtilisateur = None
        self.__jPanelGeneral = None
        self.__jPanelParamsGeneraux = None
        self.__jPanelPrefs = None
        self.__jRadioButtonLookJava = None
        self.__jRadioButtonLookOS = None
        self.__jTextFieldFichierSon = None
        self.__jTextFieldUtilisateur = None

        super().__init__(parent, modal)
        self.__initComponents()

        self.m_contexteResolution = contexteResolution

        self.__jTextFieldUtilisateur.setText(ENV.NOM_UTILISATEUR)

        if ENV.LOOK_INTERFACE == ENV.LOOK_INTERFACE_OS:
            self.__jRadioButtonLookOS.setSelected(True)
        else:
            self.__jRadioButtonLookJava.setSelected(True)
        self.m_iAncienLook = ENV.LOOK_INTERFACE

        self.__jCheckBoxAvertir.setSelected(ENV.AVERTIR_FIN_CALCUL)

        self.__jTextFieldFichierSon.setText(ENV.CHEMIN_FICHIER_SON_FIN_CALCUL)
        self.__jLabelFichierSon.setEnabled(ENV.AVERTIR_FIN_CALCUL)
        self.__jTextFieldFichierSon.setEnabled(ENV.AVERTIR_FIN_CALCUL)
        self.__jButtonFichierSon.setEnabled(ENV.AVERTIR_FIN_CALCUL)

        setLocationRelativeTo(None)

    #    * This method is called from within the constructor to
    #     * initialize the form.
    #     * WARNING: Do NOT modify this code. The content of this method is
    #     * always regenerated by the Form Editor.
    #     
    # <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    def __initComponents(self):
        self.__buttonGroupApparence = javax.swing.ButtonGroup()
        self.__jPanelGeneral = javax.swing.JPanel()
        self.__jPanelParamsGeneraux = javax.swing.JPanel()
        self.__jLabelUtilisateur = javax.swing.JLabel()
        self.__jTextFieldUtilisateur = javax.swing.JTextField()
        self.__jLabelApparence = javax.swing.JLabel()
        self.__jRadioButtonLookJava = javax.swing.JRadioButton()
        self.__jRadioButtonLookOS = javax.swing.JRadioButton()
        self.__jPanelPrefs = javax.swing.JPanel()
        self.__jCheckBoxAvertir = javax.swing.JCheckBox()
        self.__jLabelFichierSon = javax.swing.JLabel()
        self.__jTextFieldFichierSon = javax.swing.JTextField()
        self.__jButtonFichierSon = javax.swing.JButton()
        self.__jButtonEnregistrer = javax.swing.JButton()
        self.__jButtonAnnuler = javax.swing.JButton()
        self.__jButtonAide = javax.swing.JButton()

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE)
        setTitle("Parameter of Quantminer")
        addWindowListener(WindowAdapterAnonymousInnerClass(self))

        self.__jPanelGeneral.setLayout(None)

        self.__jPanelGeneral.setPreferredSize(java.awt.Dimension(520, 350))
        self.__jPanelParamsGeneraux.setLayout(None)

        self.__jPanelParamsGeneraux.setBorder(javax.swing.BorderFactory.createTitledBorder(None, "General Parameter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, java.awt.Font("Dialog", 3, 12)))
        self.__jLabelUtilisateur.setText("User Name:")
        self.__jPanelParamsGeneraux.add(self.__jLabelUtilisateur)
        self.__jLabelUtilisateur.setBounds(20, 30, 140, 14)

        self.__jPanelParamsGeneraux.add(self.__jTextFieldUtilisateur)
        self.__jTextFieldUtilisateur.setBounds(180, 30, 300, 19)

        self.__jLabelApparence.setText("Interface:")
        self.__jPanelParamsGeneraux.add(self.__jLabelApparence)
        self.__jLabelApparence.setBounds(20, 60, 150, 14)

        self.__buttonGroupApparence.add(self.__jRadioButtonLookJava)
        self.__jRadioButtonLookJava.setText("JAVA Style (default)")
        self.__jPanelParamsGeneraux.add(self.__jRadioButtonLookJava)
        self.__jRadioButtonLookJava.setBounds(180, 60, 153, 20)

        self.__buttonGroupApparence.add(self.__jRadioButtonLookOS)
        self.__jRadioButtonLookOS.setText("Operating System Style")
        self.__jPanelParamsGeneraux.add(self.__jRadioButtonLookOS)
        self.__jRadioButtonLookOS.setBounds(180, 80, 160, 23)

        self.__jPanelGeneral.add(self.__jPanelParamsGeneraux)
        self.__jPanelParamsGeneraux.setBounds(10, 40, 500, 120)
        self.__jPanelParamsGeneraux.getAccessibleContext().setAccessibleName("General parameters")

        self.__jPanelPrefs.setLayout(None)

        self.__jPanelPrefs.setBorder(javax.swing.BorderFactory.createTitledBorder(None, "User preference", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, java.awt.Font("Dialog", 3, 12)))
        self.__jCheckBoxAvertir.setText("Notify me at the end of a computation by a message with a sound")
        self.__jCheckBoxAvertir.addActionListener(ActionListenerAnonymousInnerClass(self))

        self.__jPanelPrefs.add(self.__jCheckBoxAvertir)
        self.__jCheckBoxAvertir.setBounds(20, 30, 470, 23)

        self.__jLabelFichierSon.setText("Sound file:")
        self.__jPanelPrefs.add(self.__jLabelFichierSon)
        self.__jLabelFichierSon.setBounds(60, 60, 80, 14)

        self.__jPanelPrefs.add(self.__jTextFieldFichierSon)
        self.__jTextFieldFichierSon.setBounds(140, 60, 240, 19)

        self.__jButtonFichierSon.setText("Load")
        self.__jButtonFichierSon.addActionListener(ActionListenerAnonymousInnerClass2(self))

        self.__jPanelPrefs.add(self.__jButtonFichierSon)
        self.__jButtonFichierSon.setBounds(390, 60, 100, 20)

        self.__jPanelGeneral.add(self.__jPanelPrefs)
        self.__jPanelPrefs.setBounds(10, 180, 500, 110)
        self.__jPanelPrefs.getAccessibleContext().setAccessibleName("User Preferences:")

        self.__jButtonEnregistrer.setText("Save")
        self.__jButtonEnregistrer.addActionListener(ActionListenerAnonymousInnerClass3(self))

        self.__jPanelGeneral.add(self.__jButtonEnregistrer)
        self.__jButtonEnregistrer.setBounds(160, 310, 100, 23)

        self.__jButtonAnnuler.setText("Cancel")
        self.__jButtonAnnuler.addActionListener(ActionListenerAnonymousInnerClass4(self))

        self.__jPanelGeneral.add(self.__jButtonAnnuler)
        self.__jButtonAnnuler.setBounds(270, 310, 100, 23)

        self.__jButtonAide.setText("?")
        self.__jButtonAide.addActionListener(ActionListenerAnonymousInnerClass5(self))

        self.__jPanelGeneral.add(self.__jButtonAide)
        self.__jButtonAide.setBounds(458, 11, 50, 23)

        getContentPane().add(self.__jPanelGeneral, java.awt.BorderLayout.CENTER)

        pack() # </editor-fold>//GEN-END:initComponents

    class WindowAdapterAnonymousInnerClass(java.awt.event.WindowAdapter):

        def __init__(self, outerInstance):
            self.__outerInstance = outerInstance

        def windowClosing(self, evt):
            outerInstance.__closeDialog(evt)

    class ActionListenerAnonymousInnerClass(java.awt.event.ActionListener):

        def __init__(self, outerInstance):
            self.__outerInstance = outerInstance

        def actionPerformed(self, evt):
            outerInstance.__jCheckBoxAvertirActionPerformed(evt)

    class ActionListenerAnonymousInnerClass2(java.awt.event.ActionListener):

        def __init__(self, outerInstance):
            self.__outerInstance = outerInstance

        def actionPerformed(self, evt):
            outerInstance.__jButtonFichierSonActionPerformed(evt)

    class ActionListenerAnonymousInnerClass3(java.awt.event.ActionListener):

        def __init__(self, outerInstance):
            self.__outerInstance = outerInstance

        def actionPerformed(self, evt):
            outerInstance.__jButtonEnregistrerActionPerformed(evt)

    class ActionListenerAnonymousInnerClass4(java.awt.event.ActionListener):

        def __init__(self, outerInstance):
            self.__outerInstance = outerInstance

        def actionPerformed(self, evt):
            outerInstance.__jButtonAnnulerActionPerformed(evt)

    class ActionListenerAnonymousInnerClass5(java.awt.event.ActionListener):

        def __init__(self, outerInstance):
            self.__outerInstance = outerInstance

        def actionPerformed(self, evt):
            outerInstance.__jButtonAideActionPerformed(evt)




    def __jCheckBoxAvertirActionPerformed(self, evt):
        bCaseAvertirCochee = False

        bCaseAvertirCochee = self.__jCheckBoxAvertir.isSelected()

        self.__jLabelFichierSon.setEnabled(bCaseAvertirCochee)
        self.__jTextFieldFichierSon.setEnabled(bCaseAvertirCochee)
        self.__jButtonFichierSon.setEnabled(bCaseAvertirCochee) #GEN-LAST:event_jCheckBoxAvertirActionPerformed



    def __jButtonAideActionPerformed(self, evt):
        dialogAide = DialogHelp(ENV.REPERTOIRE_AIDE+"parametrage.htm", None, True)
        dialogAide.show() #GEN-LAST:event_jButtonAideActionPerformed




    def __jButtonAnnulerActionPerformed(self, evt):
        setVisible(False)
        dispose() #GEN-LAST:event_jButtonAnnulerActionPerformed




    def __jButtonEnregistrerActionPerformed(self, evt):

        ENV.NOM_UTILISATEUR = self.__jTextFieldUtilisateur.getText()
        if self.m_contexteResolution is not None:
            self.m_contexteResolution.m_sNomUtilisateur = ENV.NOM_UTILISATEUR

        if self.__jRadioButtonLookOS.isSelected():
            ENV.LOOK_INTERFACE = ENV.LOOK_INTERFACE_OS
        else:
            ENV.LOOK_INTERFACE = ENV.LOOK_INTERFACE_JAVA

        ENV.AVERTIR_FIN_CALCUL = self.__jCheckBoxAvertir.isSelected()

        if ENV.AVERTIR_FIN_CALCUL:
            ENV.CHEMIN_FICHIER_SON_FIN_CALCUL = self.__jTextFieldFichierSon.getText()

        if ENV.LOOK_INTERFACE != self.m_iAncienLook:
            JOptionPane.showMessageDialog(None, "The change in the appearance will happen the next time you start the software.", "Information", JOptionPane.INFORMATION_MESSAGE)

        ENV.EnregistrerFichierParametrage()

        setVisible(False)
        dispose() #GEN-LAST:event_jButtonEnregistrerActionPerformed



    def __jButtonFichierSonActionPerformed(self, evt):
        sFichierChoisi = None

        description = []
        description.append("Sound files")
        extention = []
        extention.append("wav")

        sFichierChoisi = ToolsInterface.DialogOuvertureFichier(self, ENV.CHEMIN_FICHIER_SON_FIN_CALCUL, description, extention)

        if sFichierChoisi is not None:
            self.__jTextFieldFichierSon.setText(sFichierChoisi) #GEN-LAST:event_jButtonFichierSonActionPerformed



    #* Closes the dialog 
    def __closeDialog(self, evt):
        setVisible(False)
        dispose() #GEN-LAST:event_closeDialog

    #    *
    #     * @param args the command line arguments
    #     
    @staticmethod
    def main(args):
        (DialogParameterSetting(None, javax.swing.JFrame(), True)).show()


    # Variables declaration - do not modify//GEN-BEGIN:variables
    # End of variables declaration//GEN-END:variables

