#                                             
# *Copyright 2007, 2011 CCLS Columbia University (USA), LIFO University of Orl��ans (France), BRGM (France)
# *
# *Authors: Cyril Nortet, Xiangrong Kong, Ansaf Salleb-Aouissi, Christel Vrain, Daniel Cassard
# *
# *This file is part of QuantMiner.
# *
# *QuantMiner is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
# *
# *QuantMiner is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
# *
# *You should have received a copy of the GNU General Public License along with QuantMiner.  If not, see <http://www.gnu.org/licenses/>.
# 

from src.tools import *




class DialogAbout(javax.swing.JDialog):

    #default serial
    __serialVersionUID = 1
    #* Creates new form DialogAPropos 
    def __init__(self, parent, modal):
        self.__jButtonOK = None
        self.__jLabelLogoCCLS = None
        self.__jLabelLogoLIFO = None
        self.__jLabelLogoBRGM = None
        self.__jPanelGeneral = None
        self.__jTextAreaAProposTitle = None
        self.__jTextAreaAProposSubTitle = None
        self.__jTextAreaAPropos = None

        super().__init__(parent, modal)

        sTexteAPropos = None
        sTexteAProposTitle = None
        sTexteAProposSubTitle =None
        self.__initComponents()

        sTexteAProposTitle = "QuantMiner version "+ENV.VERSION_QUANTMINER
        sTexteAProposSubTitle = "Distributed under GPL License, Version 3"
        sTexteAPropos = "\n\nStudents:	Cyril Nortet and Xiangrong Kong" + "\nAdvisors:	Ansaf Salleb-Aouissi (CCLS, Columbia University)\n" + "	Christel Vrain (LIFO, University of Orleans)\n" + "	Daniel Cassard (BRGM, France)"

        self.__jTextAreaAPropos.setText(sTexteAPropos)
        self.__jTextAreaAProposTitle.setText(sTexteAProposTitle)
        self.__jTextAreaAProposSubTitle.setText(sTexteAProposSubTitle)

        self.__jLabelLogoCCLS.setIcon(javax.swing.ImageIcon(ENV.REPERTOIRE_RESSOURCES + "logoCCLS.jpg"))
        self.__jLabelLogoLIFO.setIcon(javax.swing.ImageIcon(ENV.REPERTOIRE_RESSOURCES + "logoLIFO.png"))
        self.__jLabelLogoBRGM.setIcon(javax.swing.ImageIcon(ENV.REPERTOIRE_RESSOURCES + "logoBRGM.jpg"))
        setLocationRelativeTo(None)

    #    * This method is called from within the constructor to
    #     * initialize the form.
    #     * WARNING: Do NOT modify this code. The content of this method is
    #     * always regenerated by the Form Editor.
    #     
    # <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    def __initComponents(self):
        self.__jPanelGeneral = javax.swing.JPanel()
        self.__jTextAreaAPropos = javax.swing.JTextArea()
        self.__jTextAreaAProposTitle = javax.swing.JTextArea()
        self.__jTextAreaAProposSubTitle = javax.swing.JTextArea()
        self.__jLabelLogoCCLS = javax.swing.JLabel()
        self.__jLabelLogoLIFO = javax.swing.JLabel()
        self.__jLabelLogoBRGM = javax.swing.JLabel()
        self.__jButtonOK = javax.swing.JButton()

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE)
        setTitle("About QuantMiner")
        setResizable(False)
        addWindowListener(WindowAdapterAnonymousInnerClass(self))

        self.__jPanelGeneral.setLayout(None)

        self.__jPanelGeneral.setBackground(java.awt.Color(255, 255, 255))
        self.__jPanelGeneral.setPreferredSize(java.awt.Dimension(500, 320))

        self.__jTextAreaAPropos.setEditable(False)
        self.__jTextAreaAPropos.setFont(java.awt.Font("Dialog", java.awt.Font.PLAIN, 12))
        self.__jTextAreaAPropos.setBounds(60, 150, 460, 100)
        self.__jPanelGeneral.add(self.__jTextAreaAPropos)

        self.__jTextAreaAProposTitle.setEditable(False)
        self.__jTextAreaAProposTitle.setFont(java.awt.Font("Dialog", java.awt.Font.BOLD, 16))
        self.__jTextAreaAProposTitle.setBounds(150, 15, 200, 25)
        self.__jPanelGeneral.add(self.__jTextAreaAProposTitle)


        self.__jTextAreaAProposSubTitle.setEditable(False)
        self.__jTextAreaAProposSubTitle.setFont(java.awt.Font("Dialog", java.awt.Font.PLAIN, 11))
        self.__jTextAreaAProposSubTitle.setBounds(140, 45, 250, 25)
        self.__jPanelGeneral.add(self.__jTextAreaAProposSubTitle)


        self.__jLabelLogoCCLS.setBackground(java.awt.Color(255, 255, 255))
        self.__jPanelGeneral.add(self.__jLabelLogoCCLS)
        self.__jLabelLogoCCLS.setBounds(30, 60, 180, 100)

        self.__jLabelLogoLIFO.setBackground(java.awt.Color(255, 255, 255))
        self.__jPanelGeneral.add(self.__jLabelLogoLIFO)
        self.__jLabelLogoLIFO.setBounds(220, 60, 100, 100)

        self.__jLabelLogoBRGM.setBackground(java.awt.Color(255, 255, 255))
        self.__jPanelGeneral.add(self.__jLabelLogoBRGM)
        self.__jLabelLogoBRGM.setBounds(350, 60, 100, 100)


        self.__jButtonOK.setText("OK")
        self.__jButtonOK.addActionListener(ActionListenerAnonymousInnerClass(self))

        self.__jPanelGeneral.add(self.__jButtonOK)
        self.__jButtonOK.setBounds(190, 270, 100, 23)

        getContentPane().add(self.__jPanelGeneral, java.awt.BorderLayout.CENTER)

        pack() # </editor-fold>//GEN-END:initComponents

    class WindowAdapterAnonymousInnerClass(java.awt.event.WindowAdapter):

        def __init__(self, outerInstance):
            self.__outerInstance = outerInstance

        def windowClosing(self, evt):
            outerInstance.__closeDialog(evt)

    class ActionListenerAnonymousInnerClass(java.awt.event.ActionListener):

        def __init__(self, outerInstance):
            self.__outerInstance = outerInstance

        def actionPerformed(self, evt):
            outerInstance.__jButtonOKActionPerformed(evt)

    def __jButtonOKActionPerformed(self, evt):
        setVisible(False)
        dispose() #GEN-LAST:event_jButtonOKActionPerformed

    #* Closes the dialog 
    def __closeDialog(self, evt):
        setVisible(False)
        dispose() #GEN-LAST:event_closeDialog

    #    *
    #     * @param args the command line arguments
    #     
    @staticmethod
    def main(args):
        (DialogAbout(javax.swing.JFrame(), True)).show()


    # Variables declaration - do not modify//GEN-BEGIN:variables
    # End of variables declaration//GEN-END:variables

